### ISSUE TITLE
Regarding ReadMe update

### ISSUE THREAD

**Issue by yogeshnile** [aydinnyunus/WhatsappBOT#6]
readme file not good looking. can I update readme file?

**Comment by aydinnyunus** [comment]
If you send pull request.I will check it.Thank you !

YOGESH NILE <notifications@github.com>, 29 Tem 2020 Çar, 12:37 tarihinde
şunu yazdı:

**Comment by yogeshnile** [comment]
#7 issue solved please check it.

**Comment by aydinnyunus** [comment]
Thank you for help.I'm appreciated.
