### ISSUE TITLE
Phone number format

### ISSUE THREAD

**Issue by gatopadre** [aydinnyunus/WhatsappBOT#8]
I try to use de app for chilean number with this format +569XXXXYYYY, the app told me ERROR: Please enter 12 digits for Phone number. Can you help me to solve that?... Thanks

**Comment by aydinnyunus** [comment]
Delete the "if len(str(phone_number)) != 12:
            m1 = tk.Label(master,
                          text="ERROR : Please enter 12 digits for Phone Number.", fg="red", bg="black")"

parts in the WhatsappBot.py file. (line 100-103,284-285) and try again.

**Comment by gatopadre** [comment]
I already modified the if sentence to `if len(str(phone_number)) > 11:`, and also i change the message. Thanks a lot!

**Comment by aydinnyunus** [comment]
i fixed that with `if len(str(phone_number)) < 9`

**Comment by aydinnyunus** [comment]
no problem
